### ISSUE TITLE
Add support for STM32F730

### ISSUE THREAD

**Issue by folknology** [adamgreig/stm32ral#10]
From [Twitter comment](https://twitter.com/adamgreig/status/1133784824685027329) : "Looks like the latest f7 SVD (on the product page for the f730) has the 730 in it, so that zip file in stm32-rs needs updating. If you open an issue I'll try and get to it this weekend, or you could go ahead with a PR"

**Comment by adamgreig** [comment]
Better late than never, today's 0.4.0 release adds STM32F730 support at last.
