### ISSUE TITLE
RTFM support

### ISSUE THREAD

**Issue by adamgreig** [adamgreig/stm32ral#4]
This crate is almost compatible with RTFM but needs to implement a couple more things to look enough like an svd2rust crate:

* A `Peripherals {}` struct at the top level
* A `steal()` function on the `Peripherals` struct

**Comment by perlindgren** [comment]
It would be very interesting to see RTFM running on-top of the stm32ral. One huge usability problem is the lack of completions by RLS regarding register access, perhaps that can be salvaged by the simpler abstraction provided by ral.

Did you already start looking into Peripherals/steal (seems like relatively low hanging fruit)?

Best regards,
  Per

**Comment by adamgreig** [comment]
This is now working with the new `rtfm` feature; it exports a `Peripherals` struct which contains an instance of every peripheral already taken (similar to svd2rust crates), which works with rtfm `device` and resources etc.
