### ISSUE TITLE
Reset flag has no counterpart like Enabled/Disabled

### ISSUE THREAD

**Issue by pftbest** [adamgreig/stm32ral#7]
For example to reset SPI I need to do two operations:
First set Reset flag:
```Rust
let rcc2 = stm32ral::rcc::RCC::take().unwrap();
modify_reg!(stm32ral::rcc, rcc2, APB1RSTR, SPI2RST: Reset);
```
Then I need to clear it:
```Rust
modify_reg!(stm32ral::rcc, rcc2, APB1RSTR, SPI2RST: 0);
```

But there is no constant defined for this, so I have to use literal `0` instead. It would be great to have a flag like ResetClear for example.

**Comment by adamgreig** [comment]
Good point, probably just `Clear` would work even. This would need to be fixed in [stm32-rs](https://github.com/stm32-rs/stm32-rs) upstream, i.e. by adding some `Clear` values to this field, and then stm32ral could be updated.
